"""v4_8_9_initial_schema

Revision ID: 2334dcf313d1
Revises: 
Create Date: 2026-08-16 02:08:07.397196

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2334dcf313d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automute_counters',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('banned_sticker_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('pack_name', sa.String(length=255), nullable=False),
    sa.Column('punishment', sa.String(length=16), nullable=False),
    sa.Column('mute_duration', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by_mod_id', sa.BigInteger(), nullable=True),
    sa.Column('added_via', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banned_sticker_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banned_sticker_packs_chat_id'), ['chat_id'], unique=False)

    op.create_table('chat_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('hashtag', sa.String(length=64), nullable=True),
    sa.Column('report_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('warns_to_mute', sa.Integer(), nullable=True),
    sa.Column('mute_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('warns_to_ban', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_report_chat', sa.Boolean(), nullable=False),
    sa.Column('cas_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('link_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('link_filter_action', sa.String(length=16), nullable=False),
    sa.Column('auto_delete_commands', sa.Boolean(), nullable=False),
    sa.Column('warn_decay_days', sa.Integer(), nullable=False),
    sa.Column('night_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('night_mode_start', sa.String(length=5), nullable=False),
    sa.Column('night_mode_end', sa.String(length=5), nullable=False),
    sa.Column('night_mode_permissions', sa.Text(), nullable=True),
    sa.Column('night_mode_saved_permissions', sa.Text(), nullable=True),
    sa.Column('night_mode_currently_active', sa.Boolean(), nullable=False),
    sa.Column('night_mode_tz', sa.String(length=64), nullable=False),
    sa.Column('night_mode_weekend_start', sa.String(length=5), nullable=True),
    sa.Column('night_mode_weekend_end', sa.String(length=5), nullable=True),
    sa.Column('night_mode_notify', sa.Boolean(), nullable=False),
    sa.Column('night_mode_notify_enter_msg', sa.Text(), nullable=True),
    sa.Column('night_mode_notify_exit_msg', sa.Text(), nullable=True),
    sa.Column('night_mode_slow_mode_delay', sa.Integer(), nullable=False),
    sa.Column('day_slow_mode_delay', sa.Integer(), nullable=False),
    sa.Column('night_mode_saved_slow_mode_delay', sa.Integer(), nullable=True),
    sa.Column('sanitary_days', sa.Text(), nullable=True),
    sa.Column('sanitary_days_saved_permissions', sa.Text(), nullable=True),
    sa.Column('sanitary_days_currently_active', sa.Boolean(), nullable=False),
    sa.Column('sanitary_days_enabled', sa.Boolean(), nullable=False),
    sa.Column('day_permissions', sa.Text(), nullable=True),
    sa.Column('sanitary_days_permissions', sa.Text(), nullable=True),
    sa.Column('last_sanitary_month', sa.String(length=7), nullable=True),
    sa.Column('alarm_currently_active', sa.Boolean(), nullable=False),
    sa.Column('alarm_saved_permissions', sa.Text(), nullable=True),
    sa.Column('alarm_saved_slow_mode_delay', sa.Integer(), nullable=True),
    sa.Column('alarm_active_until', sa.DateTime(), nullable=True),
    sa.Column('alarm_started_by', sa.BigInteger(), nullable=True),
    sa.Column('via_bot_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('via_bot_rate_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('via_bot_mute_minutes', sa.Integer(), nullable=False),
    sa.Column('mod_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_mod_chat', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('github_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pat_encrypted', sa.Text(), nullable=True),
    sa.Column('repo_owner', sa.String(length=128), nullable=True),
    sa.Column('repo_name', sa.String(length=128), nullable=True),
    sa.Column('project_node_id', sa.String(length=64), nullable=True),
    sa.Column('project_number', sa.Integer(), nullable=True),
    sa.Column('project_owner_login', sa.String(length=128), nullable=True),
    sa.Column('project_status_option_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idea_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=255), nullable=True),
    sa.Column('tg_display_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('idea_text', sa.String(length=200), nullable=False),
    sa.Column('github_issue_url', sa.String(length=512), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_project_item_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bot_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_log', schema=None) as batch_op:
        batch_op.create_index('ix_idea_log_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_idea_log_tg_user_id', ['tg_user_id'], unique=False)

    op.create_table('keyword_watch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('phrase', sa.String(length=255), nullable=False),
    sa.Column('ban_in_night_mode', sa.Boolean(), nullable=False),
    sa.Column('rules_section', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_watch', schema=None) as batch_op:
        batch_op.create_index('ix_keyword_watch_chat_id', ['chat_id'], unique=False)
        batch_op.create_index('ix_keyword_watch_is_active', ['is_active'], unique=False)

    op.create_table('link_allowlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link_allowlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_allowlist_chat_id'), ['chat_id'], unique=False)

    op.create_table('moderators',
    sa.Column('mod_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('mod_id')
    )
    op.create_table('permission_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('slow_mode_delay', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_presets_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_permission_presets_scope'), ['scope'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('web_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_su', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_first_name', sa.String(length=255), nullable=True),
    sa.Column('tg_last_name', sa.String(length=255), nullable=True),
    sa.Column('tg_username', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('tg_photo_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('auto_discovered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_users_tg_user_id'), ['tg_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_web_users_username'), ['username'], unique=True)

    op.create_table('word_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('mute_duration', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_filters_chat_id'), ['chat_id'], unique=False)

    op.create_table('punishments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mod_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('permissions_snapshot', sa.Text(), nullable=True),
    sa.Column('report_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_mod_id', sa.BigInteger(), nullable=True),
    sa.Column('consumed_by_action', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mod_id'], ['moderators.mod_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('punishments')
    with op.batch_alter_table('word_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_filters_chat_id'))

    op.drop_table('word_filters')
    with op.batch_alter_table('web_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_users_username'))
        batch_op.drop_index(batch_op.f('ix_web_users_tg_user_id'))

    op.drop_table('web_users')
    op.drop_table('users')
    with op.batch_alter_table('permission_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_presets_scope'))
        batch_op.drop_index(batch_op.f('ix_permission_presets_name'))

    op.drop_table('permission_presets')
    op.drop_table('moderators')
    with op.batch_alter_table('link_allowlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_allowlist_chat_id'))

    op.drop_table('link_allowlist')
    with op.batch_alter_table('keyword_watch', schema=None) as batch_op:
        batch_op.drop_index('ix_keyword_watch_is_active')
        batch_op.drop_index('ix_keyword_watch_chat_id')

    op.drop_table('keyword_watch')
    with op.batch_alter_table('idea_log', schema=None) as batch_op:
        batch_op.drop_index('ix_idea_log_tg_user_id')
        batch_op.drop_index('ix_idea_log_created_at')

    op.drop_table('idea_log')
    op.drop_table('github_settings')
    op.drop_table('chat_settings')
    op.drop_table('chat_admins')
    with op.batch_alter_table('banned_sticker_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banned_sticker_packs_chat_id'))

    op.drop_table('banned_sticker_packs')
    op.drop_table('automute_counters')
    # ### end Alembic commands ###
